language: ruby
bundler_args: --without development
before_install: rm Gemfile.lock || true
rvm:
  - 2.1.0
script: bundle exec rake test
env:
  - PUPPET_VERSION="~> 3.6.0" STRICT_VARIABLES=yes FACTER_GEM_VERSION="~> 2.2.0"
  - PUPPET_VERSION="~> 3.8.3" STRICT_VARIABLES=yes FACTER_GEM_VERSION="~> 2.4.0"
sudo: false
