name 'buzzdeee-rarpd'
version '0.1.0'
source 'https://github.com/buzzdeee/buzzdeee-rarpd.git'
author 'buzzdeee'
license 'Apache 2.0'
summary 'Puppet Module to manage rarpd'
description 'Puppet Module to manage rarpd'
project_page 'https://github.com/buzzdeee/buzzdeee-rarpd'
dependency 'puppetlabs/concat', '>= 1.1.0'
